name: Dream City Church
favicon: null
layout_spectrum: 0.7782376343384385
typography_spectrum: 0.6287966724485159
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.19286795449443161
  lightness: 0.3637034948915243
  saturation: 0.4421315516810864
  rhythmicContrast: 0.5851985269691795
purpose: []
